OBJ = aux.o  collector.o  correl.o  edit_tf.o  EX.o  EXf.o  EXr.o  globers.o  HS.o  io.o  MAP.o  PK.o  sacinspect.o
LIBS = -lmblibsac -lm -lX11 -lpng -lcpgplot -lmblibgr
BIN = ../bin/sacinspect

CFLAGS=-I. -I../mblibgr/ -I../mblibsac/ -Wall -L../mblibsac -L../mblibgr

all: $(OBJ)
	$(CC) -o $(BIN) $(CFLAGS) $(OBJ) $(LIBS)
	@echo "\nDone $(shell pwd)\n"

clean:
	rm -f $(OBJ) $(BIN)
