OBJ = diskwork.o  filelist.o  sacrename.o
LIBS = -lmblibsac -lm 
BIN = ../bin/sacrename

CFLAGS=-I. -I../mblibgr/ -I../mblibsac/ -Wall -L../mblibsac -L../mblibgr

all: $(OBJ)
	$(CC) -o $(BIN) $(CFLAGS) $(OBJ) $(LIBS)
	@echo "\nDone $(shell pwd)\n"

clean:
	rm -f $(OBJ) $(BIN)
